version: '3'

services:
  app:
      build: ./server
      #image: myapp
      ports:
        - "3001:3001"

      environment:
      - DB_USER=root
      - DB_PASSWORD=changeit
      - DB_Host=db

      networks:
      - mynet

      depends_on:
      - db

  db:
      image: stackupiss/northwind:v1
      volumes:
      - myvol2:/var/lib/mysql

      networks:
      -mynet

networks:
  mynet:


volumes:
  myvol2: